version: "3"
services:
  nodejs:
    build: .
    ports:
      - "3030:3030"
    networks:
      - app-network
  db:
    image: mongo:4.2
    container_name: mongo
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
volumes:
  dbdata:
