version: "3"
services:
  nodejs:
    container_name: kate_node_2
    build: .
    ports:
      - "3234:3234"
    networks:
      - app-network
  db:
    image: mongo:4.2
    container_name: kate_mongo_2
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
networks:
  app-network:
volumes:
  dbdata:
